general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(32, 36, 44, 1.0)
}

label {
    monitor =
    text = $TIME

    color = rgba(236, 239, 244, 1.0)
    font_family = FiraCode Nerd Font Mono
    font_size = 72

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER

    color = rgba(136, 192, 208, 1.0)
    font_family = FiraCode Nerd Font Mono
    font_size = 20

    position = 0, 30
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 300, 50
    outline_thickness = 2

    inner_color = rgba(46, 52, 64, 1.0)
    outer_color = rgba(76, 86, 106, 1.0)
    font_color = rgba(216, 222, 233, 1.0)

    check_color = rgba(163, 190, 140, 1.0)
    fail_color = rgba(191, 97, 106, 1.0)

    font_family = FiraCode Nerd Font Mono

    rounding = 8
    dots_center = true
    fade_on_empty = false

    placeholder_text = Parola
    fail_text = Hatalı parola

    position = 0, -60
    halign = center
    valign = center
}
